meta_product_name: "SHARED.RUN"
meta_title: "Run Together - Anytime, Anywhere"
meta_description: "We came up with shared.run given the lack of flexibility of finding a running buddy - whether that's finding a suitable location, time or partner for you."
meta_image: "logo.jpg"
